' This is for diagrams that do not support <style>s. 

'To find a keyword
'java -jar ~/.vscode/extensions/jebbs.plantuml-2.13.6/plantuml.jar -language | grep -i ...
' Also, default values are in plantuml.jar/skin/*.skin files

!$httpGet = "<back:grey><color:grey>-<color:white>GET<color:grey>-</color></back>" 
!$http200 = "<back:#physical><color:#physical>-<color:#green>200<color:#physical>-</color></back>" 
!$http404 = "<back:red><color:red>-<color:white>404<color:red>-</color></back>" 
!$httpRedirect1 = "<back:purple><color:purple>-<color:white>301<color:purple>-</color></back>" 
!$httpRedirect2 = "<back:purple><color:purple>-<color:white>↳ 301<color:purple>-</color></back>" 

' warning! breaks newpage stuff
!pragma teoz true

skinparam BoxPadding 10
skinparam ParticipantPadding 5
'skinparam Padding 5

' set for Divider only 
skinparam Shadowing false

' skinparam monochrome reverse
' skinparam WrapWidth 100
' skinparam NoteBorderColor #BD0031
' skinparam NoteBackgroundColor #BD0031

!define _MK_DGREY #454645
!define _MK_GREY #ABB2B9
!define _MK_LGREY #EAECEE
!define _MK_NOTE_BG #FCF3CF
!define _MK_NOTE_BORDER #B7950B

skinparam class {
    ArrowColor _MK_DGREY
    ArrowFontSize 11
    HeaderBackgroundColor _MK_LGREY
    BackgroundColor #white
    BorderColor _MK_GREY
    BorderThickness 1
    'AttributeIconSize 0
    'AttributeFontColor #red
}

skinparam stereotypeCBackgroundColor _MK_LGREY
skinparam StereotypeCBorderColor _MK_GREY
' skinparam CircledCharacterRadius 10
' skinparam CircledCharacterFontColor #red
skinparam StereotypeEBackgroundColor #implementation
skinparam StereotypeEBorderColor #implementation

skinparam note {
    BorderColor _MK_NOTE_BORDER
    BackgroundColor _MK_NOTE_BG
}

skinparam package {
    BackGroundColor white
    BorderColor _MK_LGREY
    BorderThickness 1
    FontSize 11
    FontColor _MK_GREY
}
